version: 2
updates:
    open-pull-requests-limit: 25
  - package-ecosystem: npm
    directory: /mobile
    schedule:
      interval: monthly
    open-pull-requests-limit: 25
  - package-ecosystem: cargo
    directory: /api
    schedule:
      interval: monthly
    open-pull-requests-limit: 25
  - package-ecosystem: npm
    directory: /nextweb
    schedule:
      interval: monthly
    open-pull-requests-limit: 25
