/*
 Generated by typeshare 1.7.0
*/

export interface UserModel {
  model: {
    _id: {
      $oid: string;
    };
    first_name: string;
    last_name: string;
    email: string;
    password: string;
  };
  token: string;
  refresh: string;
}

export enum ExerciseType {
  Weight = 'Weight',
  Time = 'Time',
}

export interface ExerciseModel {
  _id: { $oid: string };
  title: string;
  description: string;
  exercise_type: ExerciseType;
}

export enum SetType {
  Default = 'Default',
  WarmUp = 'WarmUp',
  DropSet = 'DropSet',
  Failure = 'Failure',
}

export const ExerciseTypes = ['Legs', 'Biceps', 'Back', 'Shoulders', 'Triceps', 'Chest'];

export interface WorkoutModelExerciseSet {
  set_type: SetType;
  weight: number;
  reps: number;
  time: number;
}

export interface WorkoutModelExerciseSet2 {
  set_type: string;
  weight: number;
  reps: number;
  time: number;
}

export interface WorkoutModelExercise {
  exercise_id: { $oid: string };
  note: string;
  sets: WorkoutModelExerciseSet[];
}

export interface WorkoutModel {
  _id: string;
  user_id: string;
  title: string;
  note: string;
  exercises: WorkoutModelExercise[];
  started_at: string;
  finished_at: string;
}

export interface WorkoutModelOutput {
  _id: string;
  user_id: string;
  title: string;
  note: string;
  exercises: WorkoutModelExercise[];
  started_at: Date;
  finished_at: Date;
}

export interface PreviousExercises {
  _id: { $oid: string };
  sets: WorkoutModelExerciseSet2[];
}

export interface PreviousExercisesList {
  list: PreviousExercises[];
}

export interface Routines {
  user_id: string;
  title: string;
  exercises: { title: string; exercise_id: string }[];
}

export interface RoutinesInput {
  list: { title: string; exercises: { title: string; exercise_id: string }[] }[];
}
