/*
 Generated by typeshare 1.7.0
*/

export enum ExerciseType {
  Weight = 'Weight',
  Time = 'Time',
}

export interface ExerciseModel {
  _id: string;
  title: string;
  description: string;
  exercise_type: ExerciseType;
}

export enum SetType {
  Default = 'Default',
  WarmUp = 'WarmUp',
  DropSet = 'DropSet',
  Failure = 'Failure',
}

export interface WorkoutModelExerciseSet {
  set_type: SetType;
  weight: number;
  reps: number;
  time: number;
}

export interface WorkoutModelExercise {
  exercise_id: string;
  note: string;
  sets: WorkoutModelExerciseSet[];
}

export interface WorkoutModel {
  _id: string;
  user_id: string;
  title: string;
  note: string;
  exercises: WorkoutModelExercise[];
  started_at: Date;
  finished_at: Date;
}
