GET http://localhost:3000/users/6564f90190b518f2960e5faa/workouts
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3MDE1MzAzNjYsImlhdCI6MTcwMTUyNDM2NiwiaXNzdWVyIjoiaG91Z2UifQ.CJj_AtCAc1O5Th6ErDOSS5lXJCWMyV7UFxmfTRrmshY